# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV.fetch('DATABASE_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { '' }%>
  host: <%= ENV.fetch('DATABASE_HOST') { 'postgis' } %>

development:
  <<: *default
  database: where-is-my-store_development

test:
  <<: *default
  database: where-is-my-store_test

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') { 'where-is-my-store_production' } %>
